### ISSUE TITLE
Velocity acts weird if the target object is higher than ground level

### ISSUE THREAD

**Issue by allaith-san** [Frank01001/Unity---HL-A-Gravity-Gloves-Basic-Implementation#1]
hey there, first of all, thanks for this amazing project 
however, I have this problem where if I try to attract the target (cube) and its not on the ground level (maybe above a table or another object) the cube fly at the speed of light above the player instead of targeting the hands but if the cube was on the ground everything works just fine!

**Comment by allaith-san** [comment]
After playing around with values I was able to fix it by returning a different velocity depending on the difference between start and vertex vectors :
![image](https://user-images.githubusercontent.com/18726549/99809819-221c1100-2b43-11eb-8b69-bd9456d09c46.png)

**Comment by Frank01001** [comment]
Thanks! It's been a couple of months since I last worked on the project. My aim was to cover the physics and math behind the Gravity Gloves and not to build a fully polished implementation, so I didn't test and reorganize the code much.

Besides, since the Half Life Alyx Developer Commentary update came out, I discovered a couple of tricks the developers used to make the usage much more comfortable and precise.
